### ISSUE TITLE
Printing a single node

### ISSUE THREAD

**Issue by dave** [dave/dst#24]
This is problematic because only `*ast.File` stores comments. If we convert a `dst.Expr` to an `ast.Expr`, there's nowhere to put the comments so they will be lost. Workarounds? For `Decl` perhaps we could create an empty `File` with one `Decl`, but what for `Stmt` and `Expr`?

**Comment by jordanlewis** [comment]
Hey @dave, is this closed as a wontfix? I'm running into this issue in my project - especially for testing, it's frustrating to not have an easy way to pretty print a single node.

**Comment by jordanlewis** [comment]
Even a shortcut to print a `dst.Node` without its comments would be super useful, for me. But I understand if this isn't something you can get to - thanks!

**Comment by jordanlewis** [comment]
I've been using the following in my test helper, you can imagine a similar thing for exprs or decls:

```
func prettyPrintStmts(stmts []dst.Stmt) string {
	if len(stmts) == 0 {
		return ""
	}
	f := &dst.File{
		Name: dst.NewIdent("main"),
		Decls: []dst.Decl{
			&dst.FuncDecl{
				Name: dst.NewIdent("test"),
				Type: &dst.FuncType{},
				Body: &dst.BlockStmt{
					List: stmts,
				},
			},
		},
	}
	var ret strings.Builder
	decorator.Fprint(&ret, f)
	prelude := `package main

func test() {
`
	postlude := `}
`
	s := ret.String()
	return strings.TrimSpace(s[len(prelude) : len(s)-len(postlude)])
}

```

**Comment by dave** [comment]
Yeah unfortunately any solution would have to be a kludge like your example. I think I'd rather keep things like that out of the library.

**Comment by jordanlewis** [comment]
Makes sense, thanks for the great project.

**Comment by switchupcb** [comment]
With the recent updates, will you ever plan to add a function that allows us to do this?

**Comment by switchupcb** [comment]
Also, this doesn't work with generic functions @dave 

```go
for _, decl := range funcDecls {
  newFile := &dst.File{
	  Name: dst.NewIdent("main"),
	  Decls: []dst.Decl{
		  decl,
	  },
  }

  var newBuffer strings.Builder
  decorator.Fprint(&newBuffer, newFile)
  newSrc := newBuffer.String()
  output.WriteString(strings.TrimSpace(newSrc[len(prelude):]))
  output.WriteString("\n\n")
}
```
