### ISSUE TITLE
Parse a single go file with it's all imported dependencies to a AST tree

### ISSUE THREAD

**Issue by nicholas-ling** [dave/dst#37]
Hi there, can dst parse a single go file with it's all imported dependencies to a AST tree?  I noticed "NewDecoratorWithImports" may help but when I dig into it, seems like not meet my expectation. I have an example below: 

File request.go:
`
import Team
type Request struct {
	team           Team           `json:"team"`
}`

File team.go
`
type Request struct {
	name           string           `json:"name"`
}`

What I'd like to have is to get the whole AST tree of Request with all the information of Team. Thank you.

**Comment by dave** [comment]
I’m taking a break from open source and trekking across Nepal for five months... today is the first internet I’ve had in over a month. I won’t have my laptop until September but I’ll take a look at this when I can.

However from looking at your issue it looks like something ‘dst’ should already be able to do... without my laptop it’s tricky for me to give you a code sample though! 

One question: does your code sample actually compile? Seems to me that ‘import Team’ might fail.

p.s. if you want to know more about the trek, check out my blog wildernessprime.com :)
