### ISSUE TITLE
question: astutil/inspector equivalents

### ISSUE THREAD

**Issue by ncsibra** [dave/dst#39]
Hi,

I wrote code with the standard ast, astutil and inspector packages, which gets some code from a file and adds some new blocks to a specific position, plus some imports.
Worked well, I had only one problem, wasn't able to figure out how to add a newline before the inserted block. :D
That's how I found your library.
Currently, I have a working code, which is: 
```go
package main

import (
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"

	"golang.org/x/tools/go/ast/astutil"

	"github.com/dave/dst"
	"github.com/dave/dst/decorator"
	"github.com/dave/dst/dstutil"
	"golang.org/x/tools/go/ast/inspector"
)

func main() {
	code := `package main

	import "github.com/prometheus/client_golang/prometheus/promhttp"

	func main() {
		c.echoEngine.GET("metrics", echo.WrapHandler(promhttp.Handler()))
	}
`

	newFile, err := decorator.Parse(code)
	if err != nil {
		panic(err)
	}

	var newBlockStmt *dst.BlockStmt
	for _, d := range newFile.Decls {
		f, ok := d.(*dst.FuncDecl)
		if !ok {
			continue
		}

		if f.Name.Name == "main" {
			newBlockStmt = f.Body
		}
	}

	fset := token.NewFileSet()
	origFile, err := parser.ParseFile(fset, "controller.go.source", nil, 0)
	if err != nil {
		panic(err)
	}

	blockStmt, exprStmt := healthCheckParentNodes(origFile)

	dec := decorator.NewDecorator(fset)
	dstFile, err := dec.DecorateFile(origFile)
	if err != nil {
		panic(err)
	}

	dstBlockStmt := dec.Dst.Nodes[blockStmt].(*dst.BlockStmt)
	dstExprStmt := dec.Dst.Nodes[exprStmt].(*dst.ExprStmt)

	dstutil.Apply(dstBlockStmt, func(c *dstutil.Cursor) bool {
		if c.Node() != dstExprStmt {
			return true
		}

		for i := len(newBlockStmt.List) - 1; i >= 0; i-- {
			c.InsertAfter(newBlockStmt.List[i])
		}
		return false
	}, nil)

	newSource, err := os.Create("controller_new.go.source")
	if err != nil {
		panic(err)
	}
	defer newSource.Close()

	fset, origFile, err = decorator.RestoreFile(dstFile)
	if err != nil {
		panic(err)
	}

	for _, i := range newFile.Imports {
		astutil.AddImport(fset, origFile, strings.Trim(i.Path.Value, `"`))
	}

	if err := format.Node(newSource, fset, origFile); err != nil {
		panic(err)
	}

}

func healthCheckParentNodes(f *ast.File) (blockStmt ast.Node, exprStmt ast.Node) {
	types := []ast.Node{new(ast.BasicLit)}

	ins := inspector.New([]*ast.File{f})
	ins.WithStack(types, func(n ast.Node, push bool, stack []ast.Node) (prune bool) {
		if !push || blockStmt != nil {
			return false
		}

		lit := n.(*ast.BasicLit)
		if !strings.Contains(lit.Value, "healthcheck") {
			return true
		}

		for i := len(stack) - 1; i >= 0; i-- {
			if s, ok := stack[i].(*ast.ExprStmt); ok {
				exprStmt = s
				continue
			}

			if s, ok := stack[i].(*ast.BlockStmt); ok {
				blockStmt = s
				break
			}
		}

		return false
	})

	return blockStmt, exprStmt
}
```
The input file looks like this:
```go
package rest

import (
	"net/http"
	"net/http/pprof"
	"os"
	"runtime"

	"github.com/labstack/echo"
)

type controller struct {
	echoEngine *echo.Echo
}

func NewController(echoEngine *echo.Echo) *controller {
	return &controller{echoEngine: echoEngine}
}

func (c *controller) Start() {
	if os.Getenv("DEBUG") == "true" {
		runtime.SetBlockProfileRate(1)
		runtime.SetMutexProfileFraction(5)

		c.echoEngine.GET("/debug/pprof/*", echo.WrapHandler(http.HandlerFunc(pprof.Index)))
		c.echoEngine.GET("/debug/pprof/cmdline", echo.WrapHandler(http.HandlerFunc(pprof.Cmdline)))
		c.echoEngine.GET("/debug/pprof/profile", echo.WrapHandler(http.HandlerFunc(pprof.Profile)))
		c.echoEngine.GET("/debug/pprof/symbol", echo.WrapHandler(http.HandlerFunc(pprof.Symbol)))
		c.echoEngine.GET("/debug/pprof/trace", echo.WrapHandler(http.HandlerFunc(pprof.Trace)))
	}

	c.echoEngine.Add(http.MethodGet, "/healthcheck", func(eCtx echo.Context) error {
		return eCtx.String(http.StatusOK, "ok")
	})

	c.echoEngine.Add(http.MethodGet, "/something-else", func(eCtx echo.Context) error {
		return eCtx.String(http.StatusOK, "ok")
	})
}
```
The code is way too complicated and using both the ast and dst packages, plus the inspector, so I have some questions.

First, I wasn't able to figure out how to add the import from the new code snippet to the old one. Checked the readme about resolvers, but it feels way too complicated and mainly developed for automatic import management. I just wanted to add an import manually without any magic, like the `astutil.AddImport`.
Tried to do something like `dstFile.Imports = append(dstFile.Imports, newFile.Imports...)`, but when printed out the source code with `decorator.Print(dstFile)`, the import was missing. 
Is it possible to do this with dst?

Second thing, that there is a `decorator.Decorate` function, which returns a `dst.Node`, first I used this to add the newline, but wasn't able to figure out how to convert back to an `ast.Node`, I only saw a method to restore a whole ast.file.
Is it possible? Would this work? I mean, would that keep the newline in the `ast.Node` too?

Third, I wasn't able to figure out how to replace the inspector `WithStack` method with dst related code, because I don't know how to build a stack. 
I can't see any method which tells about parent nodes during Inspect or Walk, so I don't know how the current node relates to the previous one.
Is it possible with dst?

It's a little long, sorry, checked the documentation, but didn't find the answers.

**Comment by dave** [comment]
> I had only one problem, wasn't able to figure out how to add a newline before the inserted block.

Should be pretty simple: `n.Decorations().Before = dst.EmptyLine`. See [here](https://github.com/dave/dst#decorations) in the docs.

> but it feels way too complicated and mainly developed for automatic import management

I feel your pain. Unfortunately `dst` doesn't have a way to shortcut this. You could add the `ImportSpec` nodes manually to the `import` block? There's a bunch of edge cases to think about here - take a look at [this function](https://github.com/dave/dst/blob/e3c208037a64131003377785f5ccddc79a887a29/decorator/restorer.go#L166).

> Second thing, that there is a decorator.Decorate function, which returns a dst.Node, first I used this to add the newline, but wasn't able to figure out how to convert back to an ast.Node, I only saw a method to restore a whole ast.file. Is it possible? Would this work?

I wanted to add this, but it doesn't really make sense. The comments are stored in the file, so converting a `dst.Node` to an `ast.Node` you'd lose all the comments.

> I can't see any method which tells about parent nodes during Inspect or Walk

Check out `dstutils.Apply` the `Cursor` has a `Parent()` method.

**Comment by ncsibra** [comment]
Thanks for the answer!
I meant the newline problem for the ast package, not yours, I found your lib in a newline/whitespace related golang issue. :)
I will check your suggestions, but finally, I did everything with ast and the helper packages and in the end converted the ast to dst then back to ast, without any change, that took care of the newline issue. :)
