### ISSUE TITLE
Why rewrite APIs doesn't consider references?

### ISSUE THREAD

**Issue by zhiqiangxu** [dave/dst#40]
Hello dave, I've got one question about the rewrite API for you:)

I think the `Apply(root dst.Node, pre, post ApplyFunc) (result dst.Node)` API is not as useful as it can be, one will have to do many ast node cast to do useful things, which essentially duplicates the work done in `ast.Walk` etc.

The most tricky part when rewrite is finding and replacing all its references, not just renaming the declare side, is that right?  IMHO a useful API should consider references automatically.

**UPDATE**

I find dst can automatically handle references for renaming `import`, but not `type`, `var`, `const` etc.

**Comment by dave** [comment]
Yes that's at a higher level unfortunately. The `dst` package is just a more advanced version of `ast`. To resolve references you need to use the [go/types](https://golang.org/pkg/go/types/) package.
