### ISSUE TITLE
How to import packageName path in SelectorExpr?

### ISSUE THREAD

**Issue by Breezess** [dave/dst#47]
**my code:**

	dec := decorator.NewDecoratorWithImports(token.NewFileSet(), "main", goast.New())
	f, err := dec.Parse("package test\nfunc init() {}")
	if err != nil {
		panic(err)
	}

	b := f.Decls[0].(*dst.FuncDecl).Body
	b.List = append(b.List, &dst.ExprStmt{
		X: &dst.CallExpr{
			Fun: &dst.SelectorExpr{
				X: &dst.Ident{
					Name: "Gin",
				},
				Sel: &dst.Ident{
					Name: "GET",
				},
			},
			Args: []dst.Expr{
				&dst.BasicLit{
					Kind:  token.STRING,
					Value: strconv.Quote("url"),
				},
				&dst.SelectorExpr{
					X: &dst.Ident{
						Name: "packageName",
						Path: "module/packageName",
					},
					Sel: &dst.Ident{
						Name: "functionName",
					},
				},
			},
		},
	})

	res := decorator.NewRestorerWithImports("main", guess.New())
	res.Print(f)

**result：**

package test

import "module/packageName"

func init() { Gin.Get("url", packageName.packageName.functionName) }

====
I want  Gin.Get("url", packageName.functionName)

import  is not work

**Comment by dave** [comment]
Sure... Just replace the `SelectorExpr` with an `Ident`, and specify the `Path` property. This should work:

```go
dec := decorator.NewDecoratorWithImports(token.NewFileSet(), "main", goast.New())
f, err := dec.Parse("package test\nfunc init() {}")
if err != nil {
	panic(err)
}

b := f.Decls[0].(*dst.FuncDecl).Body
b.List = append(b.List, &dst.ExprStmt{
	X: &dst.CallExpr{
		Fun: &dst.SelectorExpr{
			X: &dst.Ident{
				Name: "Gin",
			},
			Sel: &dst.Ident{
				Name: "GET",
			},
		},
		Args: []dst.Expr{
			&dst.BasicLit{
				Kind:  token.STRING,
				Value: strconv.Quote("url"),
			},
			&dst.Ident{
				Name: "functionName",
				Path: "module/packageName",
			},
		},
	},
})

res := decorator.NewRestorerWithImports("main", guess.New())
res.Print(f)
```

**Comment by dave** [comment]
See the [Imports](https://github.com/dave/dst/#imports) section in the docs:

> When adding a qualified identifier node, there is no need to use *dst.SelectorExpr - just add a *dst.Ident and set Path to the imported package path. The restorer will wrap it in a *ast.SelectorExpr where appropriate when converting back to ast, and also update the import block.

**Comment by Breezess** [comment]
@dave Thank you very much for your answer
