### ISSUE TITLE
Decorator <> AST mapping missing FuncType

### ISSUE THREAD

**Issue by jpap** [dave/dst#54]
When I decorate an AST, and then walk the DST, I encouter a `*dst.FuncType` node, but there is no mapping back to the corresponding `*ast.FuncType` node.

In `decorator/decorator-node-generated.go`, it appears that the mapping is not made in the `*ast.FuncDecl` case.

**Comment by dave** [comment]
Hey thanks for finding this. Solution looks sensible. I've merged your change and tagged as v0.26.1.

**Comment by jpap** [comment]
Thank you! :D
