### ISSUE TITLE
Better control of Load?

### ISSUE THREAD

**Issue by jpap** [dave/dst#56]
I have no need for import management, and wanted to use Load to get a DST of a package; but there is no way to configure the load and opt-out.  My (messy) workaround was to use `packages` to load the package, then decorate each `*ast.File` syntax separately, and pass around the associated decorator.

Perhaps a custom Load config is needed, that might also address #53?

**Comment by dave** [comment]
The `Load` function is a convenience function, so I'd prefer not to add complexity. I'd suggest simply copying it and customising to your needs.

**Comment by jpap** [comment]
Fair enough.  Looking at the implementation of `Load` more closely, it looks like I'd still need to be doing a lot of the work I am doing now to support cgo files: `Load` skips them altogether.
