### ISSUE TITLE
use Restorer'astMap to get astNode,but astNode.Pos() is wrong

### ISSUE THREAD

**Issue by gamife** [dave/dst#57]
`
func TestPosition(t *testing.T) {
	path := "../internal/transports/bulletin/router_bulletin.go"

	//===============================================================
	// 1: Use ast directly 
	astFset := token.NewFileSet()
	astFile, err := parser.ParseFile(astFset, path, nil, parser.ParseComments)
	if err != nil {
		log.Fatalln(err)
	}
	fmt.Print(astFile.Decls[3].Pos(), ",")
	fmt.Println(astFile.Decls[3].End())

	//===============================================================
	// 2: parse to ast, then use decorator
	dec := decorator.NewDecorator(astFset)    //包装器
	dstFile, err := dec.DecorateFile(astFile) //对astFile进行包装
	if err != nil {
		log.Fatalln(err)
	}
	fmt.Print(dec.Ast.Nodes[dstFile.Decls[3]].Pos(), ",")
	fmt.Println(dec.Ast.Nodes[dstFile.Decls[3]].End())

	//===============================================================
	// 3:  parse to dst, then use restorer
	dstFset := token.NewFileSet()
	file, err := decorator.ParseFile(dstFset, path, nil, parser.ParseComments)
	if err != nil {
		log.Fatalln(err)
	}
	restorer := decorator.NewRestorer()
	_, err = restorer.RestoreFile(file)
	if err != nil {
		log.Fatalln(err)
	}
	a := restorer.Ast.Nodes[file.Decls[3]]
	fmt.Print(a.Pos(), ",")
	fmt.Println(a.End())
}`

Result: 
1942,2357
1942,2357
1845,2210  //wrong

Is this normal?

**Comment by dave** [comment]
Yes this is normal. The intention of the restorer is to get the nodes in the correct order for AST to print them correctly. Everything else about the file will be corrupt. 

What you would need to do is print the file and parse it again with AST.

**Comment by gamife** [comment]
Thanks reply and your dst!
