### ISSUE TITLE
Will the dst package be updated when generics land?

### ISSUE THREAD

**Issue by stapelberg** [dave/dst#59]
Thanks for the very useful dst package, I have used it a few times for rewriting code with great success! :)

Now that the Go language proposal https://github.com/golang/go/issues/43651 has been accepted, I was wondering what your thoughts are on updating the dst package when generics land?

Do you plan to make the required changes so that dst can read, modify and write code that uses generics? (I’m assuming changes will be required.)

Thanks,

**Comment by dave** [comment]
Hi,

I'm not really sure how much work it'll be... It could be relatively easy if the ast package doesn't receive major changes... but it was a huge undertaking to iron out all the edge cases, and took a lot of hard work to get it stable in the first place, so I'd expect even a small change to the ast package will cause some headaches for updating dst.

Dst is definitely something I would like to keep updated, however I'm going to have very little time for working on open source stuff for the rest of 2021 and most of 2022... Towards the end of 2022 I will probably have a bit more free time, but I assume it'll need to happen before that. 

I'd be more than happy for someone else to have a go at making the updates...

**Comment by stapelberg** [comment]
Thanks for the quick reply! This is good to know, and we take a look at the situation again once we know what specific changes the ast package will need :)

**Comment by stevekuznetsov** [comment]
@dave looks like your latest release handles this! Probably good to close :)
