### ISSUE TITLE
`format.Node` alternative

### ISSUE THREAD

**Issue by cezarmathe** [dave/dst#62]
Is there any alternative to `go/format`'s `format.Node` function? I couldn't find any. Any help is greatly appreciated, thank you!

**Comment by dave** [comment]
No, I don't think so. Certainly this package doesn't get involved with formatting.

**Comment by cezarmathe** [comment]
Alright. Got it.
What I'm actually looking for is being able to parse and print a single `dst.Node` which may be a statement or an expression, not a `dst.File`. Does this library implement this kind of functionality?

**Comment by cezarmathe** [comment]
Nevermind, found another solution for my problem, thanks for taking the time to look over my issue :).
Closing.

**Comment by aCLr** [comment]
@cezarmathe couild you provide your solution?

**Comment by cezarmathe** [comment]
> @cezarmathe couild you provide your solution?

I didn't find one, I went back to using the standard ast lib from go.

**Comment by aCLr** [comment]
Thanks. I've just found the same solution :D
