### ISSUE TITLE
Dst doesn't support generics

### ISSUE THREAD

**Issue by dave** [dave/dst#63]
This is not a small change, and I will be hiking in Patagonia from December 2021 until April or May 2022 without my laptop, so I won't be able to get this done until I get back.

**Comment by hawkinsw** [comment]
Thank you @dave for the great work on this package. I hope that you are enjoying your time away! I have some time to contribute to OSS and I will take a whack at adding support for Generics. I cannot guarantee how successful I will be, but it's worth a shot.

**Comment by dave** [comment]
Good luck!

**Comment by dave** [comment]
FYI I probably won't have any time in the near future to work on this, but I'm happy to assist you... However it's been almost 4 years since I wrote the code, so my recollection of exactly how it all works inside is rather hazy... I do remember some bits of it being frustratingly complicated though 😬

**Comment by dave** [comment]
It looks like dst.go was based on ast.go from go v1.11: https://github.com/dave/dst/commit/75390d20b8449b085a00b342ef6a7025e7b43f26 (although there's probably almost no changes from 1.11 to 1.17)

**Comment by dave** [comment]
Also, it sounds like Go 1.19 might have some tweaks to generics - so it might be a good idea to be aware of what they're planning: https://twitter.com/mvdan_/status/1522271576904937477

**Comment by hawkinsw** [comment]
Thanks for the feedback! I will definitely keep all that in mind! Thank you for such a quick response!

Will

**Comment by dave** [comment]
This is fixed by https://github.com/dave/dst/pull/66 - thanks @hawkinsw!
