### ISSUE TITLE
dst removes line break between /* … */ comments and package statement

### ISSUE THREAD

**Issue by stapelberg** [dave/dst#69]
When taking the example program from the README, and adding a `/* single line comment */` like so:

```go
package main

import "github.com/dave/dst/decorator"

func main() {
	code := `/* single line comment */
package a

func main(){
	var a int    // foo
	var b string // bar
}
`
	f, err := decorator.Parse(code)
	if err != nil {
		panic(err)
	}
	if err := decorator.Print(f); err != nil {
		panic(err)
	}
}
```

…the output is:

```go
/* single line comment */package a

func main() {
	var a int    // foo
	var b string // bar
}
```

Note how `package a` is now at the end of the previous line.

The same issue is reproducible with multi-line `/* … */` comments.

I tested this with github.com/dave/dst v0.27.0, which is current at the time of writing.

**Comment by stapelberg** [comment]
When setting a breakpoint on https://github.com/dave/dst/blob/bc71a763e6c47fced1dade1267b78666d1251843/decorator/restorer-generated.go#L672 in gdb and print `n.Decs`, I can see that `Before` is set to 0.

When I manually change the code to hard-code `dst.NewLine`, the rewrite works as expected:

```go
		r.applySpace(n, "Before", dst.NewLine) // n.Decs.Before)
```

So I think the question is: why does the `dst.File` not get its `Decs.Before` set correctly?

**Comment by stapelberg** [comment]
Looking at this some more with the following test program:

```go
package main

import "github.com/dave/dst/decorator"

func main() {
	code := `/*
first line
second line
last line
*/
package a

func main(){
	var a int
	/* first main line
	second main line
	last main line */
	var b string
}
`
	f, err := decorator.Parse(code)
	if err != nil {
		panic(err)
	}
	if err := decorator.Print(f); err != nil {
		panic(err)
	}
}
```

I see that for the `FileRestorer.applyDecorations` call for the second `ast.DeclStmt` in `func main`, the decorations look like this:

```
(dlv) p decorations
github.com/dave/dst.Decorations len: 2, cap: 2, [
	"/* first main line\n\tsecond main line\n\tlast main line */",
	"\n",
]
```

For comparison, the decorations for the `ast.File` node look like this:
```
(dlv) p decorations
github.com/dave/dst.Decorations len: 2, cap: 2, [
	"/*\nfirst line\nsecond line\nlast line\n*/",
	"\n",
]
```

So it seems like the `\n` is part of the `dst.Decorations` for multi-line comments, and `n.Decs.Before` being empty might be correct after all.

Maybe the issue is with restoring the decorations, then.

**Comment by dave** [comment]
I just pushed a fix to master... can you give it a try?

**Comment by dave** [comment]
I haven't worked on this codebase for several years so I'm not exactly familiar with the micro details... but I found incrementing the cursor after the decoration for any package comment fixed this problem, and didn't fail any of the other tests... If I can find some time in the next few days I'll spend a bit longer to do a little bit more research, because I'd love to understand a bit more before tagging this as a release.

**Comment by dave** [comment]
... and yes you're right, I believe the decorator is working correctly by treating an inline comment on the preceding line to the node as a comment decoration then a newline decoration (this is how it treats this type of comment elsewhere in the code).

**Comment by stapelberg** [comment]
> I just pushed a fix to master... can you give it a try?

Thank you for the fix! I just tested it and successfully verified that it fixes the issue for me :)

**Comment by matthewhughes934** [comment]
Thanks for fixing this! I was wondering if there was any chance for a new tag to include the fix? I'm asking because I found this addresses a downstream bug I found: https://github.com/segmentio/golines/issues/110

**Comment by dave** [comment]
OK done. [v0.27.3](https://github.com/dave/dst/releases/tag/v0.27.3) 

This has been sitting at the bottom of my todo list since I pushed that change!
