### ISSUE TITLE
Create arbitrary dst.Expr from any string?

### ISSUE THREAD

**Issue by gagbo** [dave/dst#73]
Hello!

Sorry if I'm using incorrect words, I'm not proficient in Golang.

## Issue

I'm currently trying to use this package to make a Go generator. Basically the Go generator parses the comment directive into a `Context` struct, that I also want to add in the AST of the target file as a function argument.

So that means that, ideally, I'd like to have a way to use a function like (the name is inspired by the feature in [Rust's syn crate](https://docs.rs/syn/latest/syn/macro.parse_quote.html)):
```go
func parseQuote(inputValue interface{}) *dst.Expr {...}
```

It's probably a tall order, so the next best thing would be
```go
func parseQuote(input string) *dst.Expr {...}
```

So that I could at least use my `Context` and `fmt.Sprintf` to reproduce a structure literal for my configuration without having to create all the nodes manually.

Is there a method to do that or must I create everything from scratch? If I have to create everything from scratch, how would I create boolean literals? I didn't find the `bool` variant in `dst.BasicLit`, and I'm not sure how I'm supposed to create it.

Thanks a lot for this package in any case!

### PS

FTR the structure I want to create a Lit from is

```go
// Context holds the configuration
// to instrument properly a function.
//
// This can be viewed as a context for the instrumentation calls
type Context struct {
	// TrackConcurrentCalls triggers the collection of the gauge for concurrent calls of the function.
	TrackConcurrentCalls bool
	// TrackCallerName adds a label with the caller name in all the collected metrics.
	TrackCallerName bool
	// AlertConf is an optional configuration to add alerting capabilities to the metrics.
	AlertConf *AlertConfiguration
}

func NewContext() Context {
	return Context{
		TrackConcurrentCalls: true,
		TrackCallerName:      true,
		AlertConf:            nil,
	}
}

// AlertConfiguration is the configuration for autometric alerting.
type AlertConfiguration struct {
	// ServiceName is the name of the Service that will appear in the alerts.
	ServiceName string
	// Latency is an optional latency target for the function
	Latency *LatencySlo
	// Success is an optional success rate target for the function
	Success *SuccessSlo
}

// LatencySlo is an objective for latency
type LatencySlo struct {
	// Target is the maximum allowed latency for the endpoint.
	Target time.Duration
	// Objective is the success rate allowed for the given latency, from 0 to 1.
	Objective float64
}

// SuccessSlo is an objective for the success rate of the function
type SuccessSlo struct {
	// Objective is the success rate allowed for the given function, from 0 to 1.
	Objective float64
}
```

**Comment by dave** [comment]
The logic inside dst just converts ast to dst... it doesn't have any logic for parsing strings. So if you have a string and want to convert it to dst you should first parse it to ast. This is what the Parse helper function does behind the scenes.

The complication is that it must have a whole file to work with... it just can't parse an expression on its own. There's no way around this unfortunately.

**Comment by gagbo** [comment]
Too bad, in my unit tests I had a workaround by making a dummy file-like string so that I can obtain the nodes using fixed offsets:

```go
	sourceCode := `
package main

func main() (i int, cannotGetLuckyCollision error) {
	fmt.Println(hello) // line comment 3
        return 0, nil
}
`
	want := "cannotGetLuckyCollision"

	sourceAst, err := decorator.Parse(sourceCode)
	if err != nil {
		t.Fatalf("error parsing the source code: %s", err)
	}

	funcNode, ok := sourceAst.Decls[0].(*dst.FuncDecl)
	if !ok {
		t.Fatalf("First node of source code is not a function declaration")
	}

```

I'll do this here too and that should be fine for my usecase, just wanted to make sure I didn't miss something obvious. Thanks for the answer :)

**Comment by dave** [comment]
Yup that's the work-around... but it's a bit of a kludge.
