### ISSUE TITLE
How should I replace only one of the decs?

### ISSUE THREAD

**Issue by eric-wang95** [dave/dst#76]
Hi dave,thank you for the dst component provided,this component solves my problem.
But I have another question. When I use `funcDecl.Decs.Start.Replace`, I will replace all the decs, but I just want to replace one of them.

here is my code:

```
func main() {
	code := `package main
//origin dec
//i want replace this dec
func main() {
	println("Hello World!")
}`
	f, err := decorator.Parse(code)
	if err != nil {
		panic(err)
	}

	f.Decls[0].(*dst.FuncDecl).Decs.NodeDecs.Start.Replace("// you can add comments at the start...")

	if err := decorator.Print(f); err != nil {
		panic(err)
	}

	//Output:
	//package main
	//
	//// you can add comments at the start...
	//func main() {
	//	println("Hello World!")
	//}

	//Expected
	//package main
	//
	////origin dec
	//// you can add comments at the start...
	//func main() {
	//	println("Hello World!")
	//}

}
```

I don't know if you can still see this issue. I hope to get your reply. :D

**Comment by dave** [comment]
Check out https://github.com/dave/dst/blob/master/decorations.go

`Start` is just a slice of strings, so you can replace one of the items by simply accessing it with slice notation `.Start[1] = "Foo"`

**Comment by eric-wang95** [comment]
> Check out https://github.com/dave/dst/blob/master/decorations.go
> 
> `Start` is just a slice of strings, so you can replace one of the items by simply accessing it with slice notation `.Start[1] = "Foo"`

thanks for the detailed explanation!  I just tested it and successfully verified that it fixes the issue for me :)
But I found a strange problem. I can replace it and writing to file using the unit test, but there was a strange error in writing the file in the project. `runtime error: slice bounds out of range [:-1]`
Anyway, thank you for your answer:D

**Comment by dave** [comment]
Can you elaborate on the error you got? Is this a bug in `dst`? Can you make a simple demo that throws the error?

**Comment by eric-wang95** [comment]
> Can you elaborate on the error you got? Is this a bug in `dst`? Can you make a simple demo that throws the error?

oooooooooh, I found this bug , this is not a problem with dst.
there is my code:
```
originDecs := funcDecl.Decs.NodeDecs.Start.All()
originDecs[0] = newDec+"\n"
```
I wanted to add a line break after replacing the original dec, so I directly add `\n`. 
In the go source code `go/printer/printer.go:617`,
```
// Handle last line: If it only contains a closing */, align it
// with the opening /*, otherwise align the text with the other
// lines.
last := lines[len(lines)-1]
closing := "*/"
i := strings.Index(last, closing) // i >= 0 (closing is always present)
if isBlank(last[0:i]) {
	// last line only contains closing */
	if lineOfStars {
		closing = " */" // add blank to align final star
	}
		lines[len(lines)-1] = prefix + closing
	}
```
my dec last line is `*/`, but I add a line break in the last dec, this line break will lead to system judgment errors when writing to files.
so, do you have any good ways to add line breaks?

**Comment by eric-wang95** [comment]
In fact, yesterday I found that there was a  lice of strings in `start`. At that time, I wanted to directly try to replace one of the index (at that time, I added \n) and then reported an error. I didn't expect it to be the reason for the line break.

**Comment by dave** [comment]
Does this help?

```go
package foo

import (
	"github.com/dave/dst"
	"github.com/dave/dst/decorator"
)

func ExampleFoo() {
	code := `package main

func main() {
	println("Hello World!")
}`
	f, err := decorator.Parse(code)
	if err != nil {
		panic(err)
	}

	expr := f.Decls[0].(*dst.FuncDecl).Body.List[0].(*dst.ExprStmt)

	expr.Decs.Start.Append("/*\nyou\ncan\nadd\nmultiline\ncomments\nlike\nthis...\n*/")
	expr.Decs.Start.Append("\n")

	if err := decorator.Print(f); err != nil {
		panic(err)
	}

	//Output:
	//package main
	//
	//func main() {
	//	/*
	//	you
	//	can
	//	add
	//	multiline
	//	comments
	//	like
	//	this...
	//	*/
	//	println("Hello World!")
	//}

}

```

**Comment by dave** [comment]
I think it's best to add the "\n" as a separate decoration, like I've done... Does that work better for you?

**Comment by eric-wang95** [comment]
I understand your thoughts now. It worked.
Thank you again for your help :)
